/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard.profile'
import { Route as DashboardMarketplaceRouteImport } from './routes/_dashboard.marketplace'
import { Route as DashboardContributionsRouteImport } from './routes/_dashboard.contributions'
import { Route as DashboardComplaintsRouteImport } from './routes/_dashboard.complaints'
import { Route as DashboardAnnouncementsRouteImport } from './routes/_dashboard.announcements'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketplaceRoute = DashboardMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContributionsRoute = DashboardContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplaintsRoute = DashboardComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof DashboardAnnouncementsRoute
  '/complaints': typeof DashboardComplaintsRoute
  '/contributions': typeof DashboardContributionsRoute
  '/marketplace': typeof DashboardMarketplaceRoute
  '/profile': typeof DashboardProfileRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/announcements': typeof DashboardAnnouncementsRoute
  '/complaints': typeof DashboardComplaintsRoute
  '/contributions': typeof DashboardContributionsRoute
  '/marketplace': typeof DashboardMarketplaceRoute
  '/profile': typeof DashboardProfileRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/_dashboard/complaints': typeof DashboardComplaintsRoute
  '/_dashboard/contributions': typeof DashboardContributionsRoute
  '/_dashboard/marketplace': typeof DashboardMarketplaceRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/announcements'
    | '/complaints'
    | '/contributions'
    | '/marketplace'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/announcements'
    | '/complaints'
    | '/contributions'
    | '/marketplace'
    | '/profile'
    | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/announcements'
    | '/_dashboard/complaints'
    | '/_dashboard/contributions'
    | '/_dashboard/marketplace'
    | '/_dashboard/profile'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/marketplace': {
      id: '/_dashboard/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof DashboardMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/contributions': {
      id: '/_dashboard/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof DashboardContributionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/complaints': {
      id: '/_dashboard/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof DashboardComplaintsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/announcements': {
      id: '/_dashboard/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardComplaintsRoute: typeof DashboardComplaintsRoute
  DashboardContributionsRoute: typeof DashboardContributionsRoute
  DashboardMarketplaceRoute: typeof DashboardMarketplaceRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardComplaintsRoute: DashboardComplaintsRoute,
  DashboardContributionsRoute: DashboardContributionsRoute,
  DashboardMarketplaceRoute: DashboardMarketplaceRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
